services:
  fastapi:
    build: fastapi/
    ports: 
      - 8000:8000
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      db-postgres:
        condition: service_healthy
    

    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    networks:
      - frontend
    container_name: streamlit
    volumes:
      - .streamlit:/.streamlit
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-postgres:
    image: postgres
    restart: always
    container_name: postgres-db
    user: postgres
    secrets:
      - db-password
    environment:
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        PGDATA: ${PGDATA}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        
    expose:
      - 5444
    ports:
      - 5444:5432 
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5 

  nginx-proxy:
    build:
      context: nginx
      args:
        - FASTAPI_SERVER_ADDR=${FASTAPI_SERVER_ADDR}
        - STREAMLIT_FRONTEND_ADDR=${STREAMLIT_FRONTEND_ADDR}
    restart: always
    container_name: nginx-proxy
    volumes:
      - ./nginx/static:/usr/share/nginx/html:ro
    ports:
      - "${API_PORT}:80"
    depends_on:
      - streamlit
      - fastapi
    networks:
      - frontend
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail  http://127.0.0.1:${API_PORT}/healthz  || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

secrets:
  db-password:
    file: db/password.txt

volumes:
  postgres:
    external: true
    name: postgres-data

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge